### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by calebdre** [reorproject/reor#32]
i've been making this list of feedback/bugs i run into or think about as i'm using the app. Not trying to bash or complain - I love the idea of this project! Just wanted to share feedback:

*   [ ] seems like the similarity panel is getting updated whenever i stop typing and blocks rendering, so it stutters a lot.  haven't looked at the code yet though so it could be because of something else. but i'm up to 6 notes and things are very jittery&#x20;
*   [ ] i get some super irrelevant similarity results - maybe up the sensitivity?
*   [ ] it'd be cool to add a shortcut to go to a previous note
    *   or even a command palette to navigate recent notes&#x20;
*   [ ] the block editor is clunky sometimes - check out what happens when i press `CMD + Enter` -> `-` -> `{any key}` at the end of a list item

<https://github.com/reorproject/reor/assets/3318929/2ec85d3f-e312-40e7-b065-f9e26c823166>

*   [ ] it would be AWESOME to have copilot-style autocomplete suggestions. especially with using the related notes as context

---

What kind of updates are you planning to add?
